(()=>{
  const {MAP,TILE_SIZE,TOTAL_FIREFLIES,areaComplete,countLights,countMemories,createAreas,hiddenLightVisible,isBlocked,nextAreaIndex}=globalThis.MoonwellCore;
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),modal=document.querySelector('#modal'),start=document.querySelector('#start'),announcement=document.querySelector('#announcement'),count=document.querySelector('#fireflies'),memoryCount=document.querySelector('#memories'),areaLabel=document.querySelector('#area'),hint=document.querySelector('#hint'),coarse=matchMedia('(pointer:coarse)'),portrait=matchMedia('(orientation:portrait)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
  const W=320,H=200,T=TILE_SIZE,map=MAP;
  const companion=new Image(),discoveries=new Image(),keeperWalk=new Image(),memories=new Image();
  companion.src='assets/keeper-companion.png';discoveries.src='assets/discoveries.png';keeperWalk.src='assets/keeper-walk.png';memories.src='assets/moon-memories.png';
  const keys={},touchKeys={},areas=createAreas();
  const totalFireflies=TOTAL_FIREFLIES;
  let player={...areas[0].start},area=0,bridge=false,runeStep=0,echoAwake=false,bellsAwake=0,starfallAwake=false,walking=false,running=false,won=false,last=0,step=0;
  const gathered=()=>countLights(areas);
  const remembered=()=>countMemories(areas);
  const allHere=()=>areaComplete(areas[area]);
  const rect=(x,y,w,h,color)=>{ctx.fillStyle=color;ctx.fillRect(x,y,w,h)};
  const say=text=>{announcement.textContent=text;hint.textContent=text};
  const wall=(x,y)=>isBlocked(x,y,area,bridge);
  const canMove=(x,y)=>!wall(x-5,y-5)&&!wall(x+5,y-5)&&!wall(x-5,y+5)&&!wall(x+5,y+5);
  function tree(x,y){rect(x+5,y+8,6,8,'#713f12');rect(x+1,y+3,14,9,'#14532d');rect(x+4,y,8,14,'#166534');rect(x+6,y+2,4,3,'#4ade80')}
  function glow(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
  function firefly(light,index){if(light.got||(light.hidden&&!hiddenLightVisible(area,echoAwake,starfallAwake)))return;const pulse=reduce.matches?1:1+Math.sin((step+index*22)/12)*.4;glow(light.x,light.y,8*pulse,'rgba(253,224,71,.16)');rect(light.x-2,light.y-2,5,5,'#fef08a');rect(light.x-1,light.y-1,2,2,'#fff')}
  function lantern(home,lit){rect(home.x-5,home.y+4,10,6,'#78350f');rect(home.x-3,home.y-8,6,13,lit?'#fef08a':'#64748b');if(lit)glow(home.x,home.y,30,'rgba(253,224,71,.18)')}
  function moonflower(flower){glow(flower.x,flower.y,18,'rgba(196,181,253,.16)');rect(flower.x-2,flower.y-4,5,9,'#c4b5fd');rect(flower.x-6,flower.y-1,4,4,'#a78bfa');rect(flower.x+3,flower.y-1,4,4,'#a78bfa')}
  function discovery(kind,x,y){if(discoveries.complete&&discoveries.naturalWidth)ctx.drawImage(discoveries,kind*24,0,24,24,x-12,y-12,24,24)}
  function memory(place,index){if(!place.memory||place.memory.got)return;const token=place.memory;const pulse=reduce.matches?1:1+Math.sin((step+index*17)/15)*.12;glow(token.x,token.y,9*pulse,'rgba(226,232,240,.13)');if(memories.complete&&memories.naturalWidth)ctx.drawImage(memories,index*24,0,24,24,token.x-12,token.y-12,24,24);else{rect(token.x-3,token.y-4,6,8,'#e2e8f0');rect(token.x-1,token.y-2,2,4,'#c4b5fd')}}
  function keeper(x,y){if(companion.complete&&companion.naturalWidth)ctx.drawImage(companion,x-18,y-28,36,44)}
  function playerKeeper(){if(keeperWalk.complete&&keeperWalk.naturalWidth){const frame=walking&&!reduce.matches&&Math.floor(step/8)%2?24:0;ctx.drawImage(keeperWalk,frame,0,24,32,player.x-12,player.y-20,24,32);return}rect(player.x-5,player.y-5,10,11,'#a78bfa');rect(player.x-3,player.y-8,6,5,'#f8fafc');rect(player.x-2,player.y-7,1,1,'#111827');rect(player.x+2,player.y-7,1,1,'#111827')}
  function rune(stone,index){const active=index===runeStep&&!echoAwake;glow(stone.x,stone.y,active?15:8,active?'rgba(216,180,254,.2)':'rgba(148,163,184,.08)');rect(stone.x-5,stone.y-5,10,10,active?'#e9d5ff':'#64748b');rect(stone.x-2,stone.y-2,4,4,active?'#7c3aed':'#334155')}
  function bell(bell,index){const lit=bell.lit;glow(bell.x,bell.y,lit?16:9,lit?'rgba(253,224,71,.18)':'rgba(125,211,252,.08)');rect(bell.x-2,bell.y-8,4,11,lit?'#fde68a':'#64748b');rect(bell.x-5,bell.y+3,10,3,lit?'#fbbf24':'#475569');rect(bell.x-1,bell.y+7,2,3,lit?'#fff7cc':'#94a3b8')}
  function draw(){const colors=['#0f172a','#172554','#1e1b4b','#172554'];rect(0,0,W,H,colors[area]);for(let row=0;row<map.length;row++)for(let col=0;col<map[row].length;col++){const x=col*T,y=row*T;if(map[row][col]==='#')tree(x,y);else{const ground=area===2?'#312e81':area===3?'#1e3a5f':area===0?'#164e63':'#155e75';const speck=area===2?'#ddd6fe':area===3?'#bae6fd':area===0?'#67e8f9':'#a5f3fc';rect(x,y,T,T,ground);rect(x+3+(row*col)%9,y+4+(row+col)%7,1,1,speck)}}const place=areas[area];if(area===1){rect(0,94,W,14,'#082f49');if(bridge)for(let x=104;x<216;x+=18){rect(x,96,13,10,'#c4b5fd');rect(x+2,98,9,6,'#e9d5ff')}discovery(1,place.flower.x,place.flower.y);moonflower(place.flower)}if(area===2){place.runes.forEach((stone,index)=>{discovery(2,stone.x,stone.y);rune(stone,index)});if(echoAwake){glow(160,126,26,'rgba(253,224,71,.1)');rect(146,98,28,5,'#a78bfa')}}if(area===3){place.bells.forEach(bell);if(starfallAwake){glow(190,105,38,'rgba(253,224,71,.08)');for(let x=126;x<252;x+=18)rect(x,104+(x/18%2)*4,3,3,'#fde68a')}}memory(place,area);lantern(place.home,allHere());if(allHere())discovery(3,place.home.x,place.home.y-12);place.lights.forEach((light,index)=>{discovery(0,light.x,light.y);firefly(light,index)});keeper(area===0?217:area===1?284:area===2?87:286,area===0?156:area===1?44:area===2?48:155);playerKeeper();ctx.fillStyle='rgba(15,23,42,.28)';ctx.fillRect(0,0,W,H);if(gathered())rect(0,0,W,H,`rgba(253,224,71,${.02*gathered()})`)}
  function arrive(next){area=next;bridge=false;player={...areas[next].start};areaLabel.textContent=`Area: ${areas[next].name}`;if(next===1)say('Moonlight wakes Moonroot Crossing. A moonflower hums beyond the water—seek its violet glow.');else if(next===2)say('The second lantern points to Whispering Hollow. Three echo-stones remember the keeper’s path: follow their violet call.');else say('The hollow lantern opens Starfall Grove. Ring each skybell to call its fallen lights from the canopy.')}
  function finish(){won=true;running=false;modal.innerHTML='<div class="card"><h2>The Moonwell shines again.</h2><p>Starfall Grove returns its bright fragments. Eight fireflies return to the Lost Lantern, and moonlight spills through every path before dawn.</p><p>The young keeper has carried the forest home—and the forest remembers the way.</p><button id="again">Walk again</button></div>';modal.hidden=false;document.querySelector('#again').onclick=()=>location.reload();say('The Lost Lantern burns bright before dawn.')}
  function touchRune(){const stone=areas[2].runes[runeStep];if(Math.hypot(player.x-stone.x,player.y-stone.y)>=15)return;runeStep++;if(runeStep===areas[2].runes.length){echoAwake=true;say('The hollow answers in three gentle echoes. A hidden firefly rises beside the old stone arch.')}else say(`An echo-stone sings. ${areas[2].runes.length-runeStep} violet call${areas[2].runes.length-runeStep===1?'':'s'} remain.`)}
  function touchBell(){for(const bell of areas[3].bells){if(!bell.lit&&Math.hypot(player.x-bell.x,player.y-bell.y)<15){bell.lit=true;bellsAwake++;if(bellsAwake===areas[3].bells.length){starfallAwake=true;say('Three skybells answer together. Two fallen lights drift down through the open canopy.')}else say(`A skybell rings above the grove. ${areas[3].bells.length-bellsAwake} still wait in the blue dark.`);break}}}
  function update(dt){let dx=0,dy=0,speed=65*dt;if(keys.up||touchKeys.up)dy-=speed;if(keys.down||touchKeys.down)dy+=speed;if(keys.left||touchKeys.left)dx-=speed;if(keys.right||touchKeys.right)dx+=speed;if(dx&&dy){dx*=.707;dy*=.707}walking=Boolean(dx||dy);if(canMove(player.x+dx,player.y))player.x+=dx;if(canMove(player.x,player.y+dy))player.y+=dy;const place=areas[area];if(place.memory&&!place.memory.got&&Math.hypot(player.x-place.memory.x,player.y-place.memory.y)<12){place.memory.got=true;memoryCount.textContent=`Memories: ${remembered()} / 3`;say(`Forest memory found. ${place.memory.text}`)}if(area===1&&!bridge&&Math.hypot(player.x-place.flower.x,player.y-place.flower.y)<16){bridge=true;say('The moonflower opens a stepping-stone path across the water.')}if(area===2&&!echoAwake)touchRune();if(area===3&&!starfallAwake)touchBell();place.lights.forEach(light=>{if(!light.got&&(!light.hidden||hiddenLightVisible(area,echoAwake,starfallAwake))&&Math.hypot(player.x-light.x,player.y-light.y)<12){light.got=true;count.textContent=`Fireflies: ${gathered()} / ${totalFireflies}`;say(allHere()?'This lantern is awake. Follow its golden glow!':`A firefly joins you! ${totalFireflies-gathered()} still wander.`)}});if(allHere()&&!won&&Math.hypot(player.x-place.home.x,player.y-place.home.y)<17){const next=nextAreaIndex(area,areas);if(next!==null)arrive(next);else finish()}}
  function loop(time){if(!running)return;const dt=Math.min(.04,(time-last)/1000||0);last=time;step++;update(dt);draw();requestAnimationFrame(loop)}
  async function begin(){if(coarse.matches&&!portrait.matches){document.body.classList.add('playing');window.scrollTo(0,1);try{if(document.fullscreenEnabled&&!document.fullscreenElement)await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{}}modal.hidden=true;running=true;last=performance.now();canvas.focus();say('Gather the scattered moonlight before dawn.');requestAnimationFrame(loop)}
  function gate(){if(coarse.matches&&portrait.matches){document.body.classList.remove('playing');modal.hidden=false;running=false}else if(!running&&!won)modal.hidden=false}start.onclick=begin;[coarse,portrait].forEach(query=>query.addEventListener('change',gate));addEventListener('keydown',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[event.key];if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(event.key))event.preventDefault();if(event.key==='Enter'&&!running&&!won&&!portrait.matches)begin();if(event.key==='j'||event.key==='J'){const notes=areas.filter(place=>place.memory?.got).map(place=>place.memory.text);say(notes.length?`Forest memories: ${notes.join(' ')} ${3-notes.length} still wait.`:'No forest memories yet. Look for pale keepsakes beside the paths.')}if(direction)keys[direction]=true});addEventListener('keyup',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[event.key];if(direction)keys[direction]=false});const touch=document.querySelector('.touch');let touchPointer;function steer(event){const bounds=touch.getBoundingClientRect(),x=event.clientX-(bounds.left+bounds.width/2),y=event.clientY-(bounds.top+bounds.height/2),direction=Math.abs(x)>Math.abs(y)?x<0?'left':'right':y<0?'up':'down';Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);touchKeys[direction]=true}function stopSteering(){touchPointer=undefined;Object.keys(touchKeys).forEach(key=>touchKeys[key]=false)}touch.addEventListener('contextmenu',event=>event.preventDefault());touch.addEventListener('pointerdown',event=>{event.preventDefault();touchPointer=event.pointerId;try{touch.setPointerCapture(event.pointerId)}catch{}steer(event)});touch.addEventListener('pointermove',event=>{if(event.pointerId===touchPointer)steer(event)});touch.addEventListener('pointerup',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('pointercancel',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('lostpointercapture',stopSteering);draw();gate()
})();
