(()=>{
  const {MAP,TILE_SIZE,TOTAL_FIREFLIES,areaComplete,canResolveEchoRune,countLights,countMemories,createAreas,createEchoReplay,createWorldObjects,hiddenLightVisible,nearPoint,nextAreaIndex}=globalThis.MoonwellCore;
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),modal=document.querySelector('#modal'),start=document.querySelector('#start'),pauseButton=document.querySelector('#pause'),echoButton=document.querySelector('#echo'),announcement=document.querySelector('#announcement'),count=document.querySelector('#fireflies'),memoryCount=document.querySelector('#memories'),areaLabel=document.querySelector('#area'),hint=document.querySelector('#hint'),coarse=matchMedia('(pointer:coarse)'),portrait=matchMedia('(orientation:portrait)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
  const W=320,H=200,T=TILE_SIZE,map=MAP;ctx.imageSmoothingEnabled=false;
  const loadArt=src=>{const image=new Image();image.src=src;return image};
  const keeperArt=loadArt('assets/moonwell-art/production/moonwell-keeper-walk-v4.png');
  const art={tree:loadArt('assets/moonwell-art/production/moonwell-tree-tile-v3.png'),firefly:loadArt('assets/moonwell-art/production/moonwell-firefly-loop-v3.png'),memory:loadArt('assets/moonwell-art/production/moonwell-memory-loop-v2.png'),moonflower:loadArt('assets/moonwell-art/production/moonwell-moonflower-v2.png'),platform:loadArt('assets/moonwell-art/production/moonwell-root-platform-tile-v3.png'),bridge:loadArt('assets/moonwell-art/production/moonwell-bridge-segment-v2.png'),rune:loadArt('assets/moonwell-art/production/moonwell-rune-stone-v2.png'),skybell:loadArt('assets/moonwell-art/production/moonwell-skybell-loop-v2.png'),sentinel:loadArt('assets/moonwell-art/production/moonwell-sentinel-tile-v4.png'),altar:loadArt('assets/moonwell-art/production/moonwell-altar-v2.png'),water:loadArt('assets/moonwell-art/production/moonwell-water-tile-v2.png')};
  const keys={},touchKeys={},areas=createAreas();
  const totalFireflies=TOTAL_FIREFLIES;
  const query=new URLSearchParams(location.search),developerScene=query.get('dev')==='scene',requestedArea=Number.parseInt(query.get('area')||'0',10);
  let player={...areas[0].start},area=0,bridge=false,worldObjects=createWorldObjects(0,false),runeStep=0,echoAwake=false,echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0},trail=[],trailClock=0,bellsAwake=0,starfallAwake=false,walking=false,facing=1,running=false,paused=false,won=false,last=0,step=0,walkClock=0;
  const gathered=()=>countLights(areas);
  const remembered=()=>countMemories(areas);
  const allHere=()=>areaComplete(areas[area]);
  const rect=(x,y,w,h,color)=>{ctx.fillStyle=color;ctx.fillRect(x,y,w,h)};
  const loaded=image=>image.complete&&image.naturalWidth;
  const animationFrame=()=>reduce.matches?0:Math.floor(step/12)%4;
  const say=text=>{announcement.textContent=text;hint.textContent=text};
  const inside=(x,y,box)=>x>=box.x&&x<box.x+box.w&&y>=box.y&&y<box.y+box.h;
  const wall=(x,y)=>worldObjects.some(object=>object.solid&&inside(x,y,object));
  const canMove=(x,y)=>!wall(x-5,y-5)&&!wall(x+5,y-5)&&!wall(x-5,y+5)&&!wall(x+5,y+5);
  const syncEchoControl=()=>{echoButton.hidden=area!==2||!running||paused||echoAwake};
  function tree(x,y){if(loaded(art.tree)){ctx.drawImage(art.tree,x,y,T,T);return}rect(x+5,y+8,6,8,'#713f12');rect(x+1,y+3,14,9,'#14532d');rect(x+4,y,8,14,'#166534');rect(x+6,y+2,4,3,'#4ade80')}
  function glow(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
  function firefly(light,index){if(light.got||(light.hidden&&!hiddenLightVisible(area,echoAwake,starfallAwake)))return;const pulse=reduce.matches?1:1+Math.sin((step+index*22)/12)*.4;glow(light.x,light.y,8*pulse,'rgba(253,224,71,.16)');if(loaded(art.firefly))ctx.drawImage(art.firefly,animationFrame()*16,0,16,16,light.x-8,light.y-8,16,16);else{rect(light.x-2,light.y-2,5,5,'#fef08a');rect(light.x-1,light.y-1,2,2,'#fff')}}
  function fairyPlatform(object){if(loaded(art.platform))ctx.drawImage(art.platform,object.x,object.y,object.w,object.h)}
  function exitOpening(home,active){if(!active)return;const pulse=reduce.matches?1:1+Math.sin(step/14)*.12;glow(home.x,home.y-4,12*pulse,'rgba(253,224,71,.16)');rect(home.x-4,home.y-12,8,12,'#fef3c7');rect(home.x-3,home.y-11,6,10,'#fef08a');rect(home.x-2,home.y-10,4,9,'#fff7cc');rect(home.x-5,home.y-1,10,2,'#ca8a04')}
  function moonflower(flower){glow(flower.x,flower.y,18,'rgba(196,181,253,.16)');if(loaded(art.moonflower))ctx.drawImage(art.moonflower,flower.x-16,flower.y-18)}
  function memory(place,index){if(!place.memory||place.memory.got)return;const token=place.memory;const pulse=reduce.matches?1:1+Math.sin((step+index*17)/15)*.12;glow(token.x,token.y,9*pulse,'rgba(226,232,240,.13)');if(loaded(art.memory))ctx.drawImage(art.memory,animationFrame()*16,0,16,16,token.x-8,token.y-8,16,16);else{rect(token.x-3,token.y-4,6,8,'#e2e8f0');rect(token.x-1,token.y-2,2,4,'#c4b5fd')}}
  function playerKeeper(){if(keeperArt.complete&&keeperArt.naturalWidth){const frame=walking&&!reduce.matches?Math.floor(walkClock/.11)%4:0;ctx.save();ctx.translate(player.x,player.y-16);ctx.scale(facing,1);ctx.drawImage(keeperArt,frame*16,0,16,16,-8,0,16,16);ctx.restore();return}rect(player.x-5,player.y-5,10,11,'#a78bfa');rect(player.x-3,player.y-8,6,5,'#f8fafc')}
  function worldObject(object){if(object.kind==='tree')tree(object.x,object.y);else if(object.kind==='platform')fairyPlatform(object);else if(object.kind==='water'){rect(object.x,object.y,T,T,'#0a1d5c');if(loaded(art.water))ctx.drawImage(art.water,object.x,object.y)}else if(object.kind==='bridge'&&loaded(art.bridge))ctx.drawImage(art.bridge,object.frame*T,0,T,T,object.x,object.y,T,T);else if(object.kind==='sentinel'&&loaded(art.sentinel))ctx.drawImage(art.sentinel,object.x,object.y,object.w,object.h)}
  function rune(stone,index){const active=!echoAwake&&((index===0&&runeStep===0)||(index===1&&runeStep===1)||(index===2&&runeStep===2));const held=echo.active&&echo.holding&&index===0;glow(stone.x,stone.y,held?18:active?15:8,held?'rgba(103,232,249,.26)':active?'rgba(216,180,254,.2)':'rgba(148,163,184,.08)');if(loaded(art.rune))ctx.drawImage(art.rune,stone.x-16,stone.y-18)}
  function echoKeeper(){if(!echo.active)return;const pulse=reduce.matches?1:1+Math.sin(step/7)*.08;glow(echo.x,echo.y-8,heldRadius(pulse),'rgba(103,232,249,.16)');ctx.save();ctx.globalAlpha=echo.holding?.56:.38;ctx.translate(echo.x,echo.y-16);if(keeperArt.complete&&keeperArt.naturalWidth)ctx.drawImage(keeperArt,0,0,16,16,-8,0,16,16);else{rect(-5,3,10,11,'#67e8f9');rect(-3,0,6,5,'#e0f2fe')}ctx.restore()}
  function heldRadius(pulse){return echo.holding?12*pulse:8*pulse}
  function bell(bell){const lit=bell.lit;glow(bell.x,bell.y,lit?16:9,lit?'rgba(253,224,71,.18)':'rgba(125,211,252,.08)');if(loaded(art.skybell))ctx.drawImage(art.skybell,animationFrame()*32,0,32,48,bell.x-16,bell.y-34,32,48)}
  function draw(){const colors=['#0f172a','#172554','#1e1b4b','#172554'];rect(0,0,W,H,colors[area]);for(let row=0;row<map.length;row++)for(let col=0;col<map[row].length;col++){const x=col*T,y=row*T;const ground=area===2?'#312e81':area===3?'#1e3a5f':area===0?'#164e63':'#155e75';const speck=area===2?'#ddd6fe':area===3?'#bae6fd':area===0?'#67e8f9':'#a5f3fc';rect(x,y,T,T,ground);rect(x+3+(row*col)%9,y+4+(row+col)%7,1,1,speck)}worldObjects.filter(object=>object.kind==='water'||object.kind==='bridge').forEach(worldObject);worldObjects.filter(object=>object.kind!=='water'&&object.kind!=='bridge').forEach(worldObject);const place=areas[area];if(area===1)moonflower(place.flower);if(area===2){place.runes.forEach(rune);echoKeeper();if(echoAwake){glow(188,128,23,'rgba(253,224,71,.1)')}}if(area===3){place.bells.forEach(bell);if(starfallAwake){glow(190,105,38,'rgba(253,224,71,.08)');if(loaded(art.altar))ctx.drawImage(art.altar,158,72)}}memory(place,area);exitOpening(place.home,allHere());place.lights.forEach(firefly);playerKeeper();ctx.fillStyle='rgba(15,23,42,.28)';ctx.fillRect(0,0,W,H);if(gathered())rect(0,0,W,H,`rgba(253,224,71,${.02*gathered()})`)}
  function arrive(next){area=next;bridge=false;worldObjects=createWorldObjects(area,bridge);player={...areas[next].start};trail=[];echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0};areaLabel.textContent=`Area: ${areas[next].name}`;if(next===1)say('Moonlight opens Moonroot Crossing. The dark water is impassable until the moonflower reveals its safe bridge.');else if(next===2)say('A lighted forest opening leads to Whispering Hollow. Touch the first violet rune, then find the second and press E or Echo.');else say('A lighted forest opening leads to Starfall Grove. Ring each skybell to call its fallen lights from the canopy.');syncEchoControl()}
  function finish(){won=true;running=false;modal.innerHTML='<div class="card"><h2>The Moonwell shines again.</h2><p>Starfall Grove returns its bright fragments. Eight fireflies return to the Lost Lantern, and moonlight spills through every path before dawn.</p><p>The young keeper has carried the forest home—and the forest remembers the way.</p><button id="again">Walk again</button></div>';modal.hidden=false;document.querySelector('#again').onclick=()=>location.reload();say('The Lost Lantern burns bright before dawn.')}
  function resume(){paused=false;pauseButton.hidden=false;modal.hidden=true;running=true;syncEchoControl();last=performance.now();canvas.focus();say('The forest waits.');requestAnimationFrame(loop)}
  function pause(){if(!running||won)return;running=false;paused=true;pauseButton.hidden=true;syncEchoControl();Object.keys(keys).forEach(key=>keys[key]=false);Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);modal.innerHTML='<div class="card"><h2>The forest waits.</h2><p>Your lantern light is safe. Take a breath, then continue when you are ready.</p><button id="resume">Continue</button><button id="restart">Start again</button></div>';modal.hidden=false;const resumeButton=document.querySelector('#resume');resumeButton.onclick=resume;document.querySelector('#restart').onclick=()=>location.reload();resumeButton.focus();say('Moonwell is paused. Press P, Escape, or Continue when you are ready.')}
  pauseButton.onclick=()=>{if(paused)resume();else pause()};
  function resolveEcho(){echoAwake=true;echo.active=false;syncEchoControl();say('Your echo holds the first rune as the third answers. A hidden firefly rises beside the old stone arch.')}
  function touchRune(){const runes=areas[2].runes;if(runeStep===0&&nearPoint(player,runes[0])){runeStep=1;say('The first echo-stone remembers your steps. Walk to the second violet rune, then press E or Echo.')}if(canResolveEchoRune(runeStep,echo.active&&echo.holding,player,runes))resolveEcho()}
  function castEcho(){if(!running||area!==2||echoAwake||echo.active)return;const runes=areas[2].runes;if(runeStep===0){say('The lantern needs a remembered path. Touch the first violet rune first.');return}if(!nearPoint(player,runes[1])){say('Stand by the second violet rune, then press E or Echo.');return}const replay=createEchoReplay(trail,runes[0]);if(!replay.length){say('The lantern cannot find the first rune in your recent steps. Touch it again, then return here.');runeStep=0;return}echo={active:true,holding:false,path:replay,index:0,x:replay[0].x,y:replay[0].y,holdTime:4.5};runeStep=2;say('A delayed echo retraces your path. Reach the third rune while it returns to hold the first.');syncEchoControl()}
  function updateEcho(dt){if(!echo.active)return;if(echo.holding){echo.holdTime-=dt;if(echo.holdTime<=0){echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0};runeStep=0;say('The echo fades into the hollow. Touch the first rune and try again.');syncEchoControl()}return}let distance=96*dt;while(distance>0&&echo.index<echo.path.length-1){const next=echo.path[echo.index+1],dx=next.x-echo.x,dy=next.y-echo.y,gap=Math.hypot(dx,dy);if(gap<=distance){echo.x=next.x;echo.y=next.y;echo.index++;distance-=gap}else{echo.x+=dx/gap*distance;echo.y+=dy/gap*distance;distance=0}}if(echo.index===echo.path.length-1){echo.x=areas[2].runes[0].x;echo.y=areas[2].runes[0].y;echo.holding=true;say('Your echo holds the first rune. Reach the third violet rune before it fades.')}}
  function touchBell(){for(const bell of areas[3].bells){if(!bell.lit&&Math.hypot(player.x-bell.x,player.y-bell.y)<15){bell.lit=true;bellsAwake++;if(bellsAwake===areas[3].bells.length){starfallAwake=true;say('Three skybells answer together. Two fallen lights drift down through the open canopy.')}else say(`A skybell rings above the grove. ${areas[3].bells.length-bellsAwake} still wait in the blue dark.`);break}}}
  function update(dt){let dx=0,dy=0,speed=65*dt;if(keys.up||touchKeys.up)dy-=speed;if(keys.down||touchKeys.down)dy+=speed;if(keys.left||touchKeys.left)dx-=speed;if(keys.right||touchKeys.right)dx+=speed;if(dx&&dy){dx*=.707;dy*=.707}if(dx)facing=dx<0?-1:1;const beforeX=player.x,beforeY=player.y;if(canMove(player.x+dx,player.y))player.x+=dx;if(canMove(player.x,player.y+dy))player.y+=dy;walking=player.x!==beforeX||player.y!==beforeY;if(walking)walkClock+=dt;const place=areas[area];if(area===2){trailClock+=dt;if(walking||trailClock>.08){trail.push({x:player.x,y:player.y});trailClock=0;if(trail.length>1800)trail.shift()}updateEcho(dt)}if(place.memory&&!place.memory.got&&Math.hypot(player.x-place.memory.x,player.y-place.memory.y)<12){place.memory.got=true;memoryCount.textContent=`Memories: ${remembered()} / 3`;say(`Forest memory found. ${place.memory.text}`)}if(area===1&&!bridge&&Math.hypot(player.x-place.flower.x,player.y-place.flower.y)<16){bridge=true;worldObjects=createWorldObjects(area,bridge);say('The moonflower reveals a safe wooden bridge across the full water crossing.')}if(area===2&&!echoAwake)touchRune();if(area===3&&!starfallAwake)touchBell();place.lights.forEach(light=>{if(!light.got&&(!light.hidden||hiddenLightVisible(area,echoAwake,starfallAwake))&&Math.hypot(player.x-light.x,player.y-light.y)<12){light.got=true;count.textContent=`Fireflies: ${gathered()} / ${totalFireflies}`;say(allHere()?'A clear forest opening shines between the trees.':`A firefly joins you! ${totalFireflies-gathered()} still wander.`)}});if(allHere()&&!won&&Math.hypot(player.x-place.home.x,player.y-place.home.y)<17){const next=nextAreaIndex(area,areas);if(next!==null)arrive(next);else finish()}}
  function loop(time){if(!running)return;const dt=Math.min(.04,(time-last)/1000||0);last=time;step+=dt*60;update(dt);draw();requestAnimationFrame(loop)}
  async function begin(){if(coarse.matches&&!portrait.matches){document.body.classList.add('playing');window.scrollTo(0,1);try{if(document.fullscreenEnabled&&!document.fullscreenElement)await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{}}paused=false;modal.hidden=true;running=true;syncEchoControl();last=performance.now();canvas.focus();say('Gather the scattered moonlight before dawn.');requestAnimationFrame(loop)}
  function gate(){if(coarse.matches&&portrait.matches){document.body.classList.remove('playing');modal.hidden=false;running=false}else if(!running&&!won)modal.hidden=false;syncEchoControl()}start.onclick=begin;echoButton.onclick=castEcho;[coarse,portrait].forEach(query=>query.addEventListener('change',gate));addEventListener('keydown',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'}[event.key];if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(event.key))event.preventDefault();if(event.key==='Enter'&&!running&&!won&&!portrait.matches)begin();if(event.key==='e'||event.key==='E')castEcho();if(event.key==='j'||event.key==='J'){const notes=areas.filter(place=>place.memory?.got).map(place=>place.memory.text);say(notes.length?`Forest memories: ${notes.join(' ')} ${3-notes.length} still wait.`:'No forest memories yet. Look for pale keepsakes beside the paths.')}if(direction)keys[direction]=true});addEventListener('keyup',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right'}[event.key];if(direction)keys[direction]=false});const touch=document.querySelector('.touch');let touchPointer;function steer(event){const bounds=touch.getBoundingClientRect(),x=event.clientX-(bounds.left+bounds.width/2),y=event.clientY-(bounds.top+bounds.height/2),direction=Math.abs(x)>Math.abs(y)?x<0?'left':'right':y<0?'up':'down';Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);touchKeys[direction]=true}function stopSteering(){touchPointer=undefined;Object.keys(touchKeys).forEach(key=>touchKeys[key]=false)}touch.addEventListener('contextmenu',event=>event.preventDefault());touch.addEventListener('pointerdown',event=>{event.preventDefault();touchPointer=event.pointerId;try{touch.setPointerCapture(event.pointerId)}catch{}steer(event)});touch.addEventListener('pointermove',event=>{if(event.pointerId===touchPointer)steer(event)});touch.addEventListener('pointerup',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('pointercancel',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('lostpointercapture',stopSteering);draw();gate()
  addEventListener('keydown',event=>{if((event.key==='p'||event.key==='P'||event.key==='Escape')&&!won){event.preventDefault();if(paused)resume();else pause()}});
  if(developerScene&&Number.isInteger(requestedArea)&&requestedArea>=0&&requestedArea<areas.length){area=requestedArea;player={...areas[area].start};bridge=area===1;worldObjects=createWorldObjects(area,bridge);runeStep=areas[2].runes.length;echoAwake=true;bellsAwake=areas[3].bells.length;starfallAwake=true;areaLabel.textContent=`Area: ${areas[area].name}`;modal.hidden=true;running=true;say(`Developer scene preview: ${areas[area].name}`);window.__moonwellAudit=Object.freeze({area:()=>area,name:()=>areas[area].name,waterBlocked:()=>wall(80,100),bridgePassable:()=>wall(160,100)===false,sentinelBlocked:()=>wall(160,110),canvas:()=>({width:W,height:H}),transition:()=>{areas[area].lights.forEach(light=>light.got=true);player={...areas[area].home};update(0);return{area,won}}});last=performance.now();requestAnimationFrame(loop)}
})();
