(()=>{
  const {MAP,TILE_SIZE,WORLD_WIDTH,WORLD_HEIGHT,RENDER_SCALE,TOTAL_FIREFLIES,MEMORY_REVEAL_LAYOUT,MEMORY_REVEAL_TIMING,WATCHER_DIALOGUE,EXIT_STATES,areaComplete,canResolveEchoRune,countLights,countMemories,createAreas,createEchoReplay,createGroundDecor,createWorldObjects,exitStateAt,hiddenLightVisible,memoryRevealBoxForPlayer,memoryRevealStateAt,nearPoint,nextAreaIndex,watcherChoiceResult}=globalThis.MoonwellCore;
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),modal=document.querySelector('#modal'),start=document.querySelector('#start'),pauseButton=document.querySelector('#pause'),echoButton=document.querySelector('#echo'),talkButton=document.querySelector('#talk'),memoryDialogue=document.querySelector('#memory-dialogue')||(()=>{const node=document.createElement('aside');node.id='memory-dialogue';node.className='memory-dialogue';node.hidden=true;node.setAttribute('aria-live','polite');node.innerHTML='<span class="memory-dialogue__icon" aria-hidden="true">✦</span><strong>FOREST MEMORY</strong><p></p>';canvas.parentElement.append(node);return node})(),announcement=document.querySelector('#announcement'),count=document.querySelector('#fireflies'),memoryCount=document.querySelector('#memories'),areaLabel=document.querySelector('#area'),hint=document.querySelector('#hint'),coarse=matchMedia('(pointer:coarse)'),portrait=matchMedia('(orientation:portrait)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');
  const W=WORLD_WIDTH,H=WORLD_HEIGHT,T=TILE_SIZE,map=MAP;ctx.imageSmoothingEnabled=false;ctx.setTransform(RENDER_SCALE,0,0,RENDER_SCALE,0,0);
  const loadArt=src=>{const image=new Image();image.src=src;return image};
  const keeperArt=loadArt('assets/moonwell-art/production/moonwell-keeper-walk-v5.png');
  const art={exitTree:loadArt('assets/moonwell-art/production/moonwell-crescent-exit-overhang-v3.png'),spruce:loadArt('assets/moonwell-art/production/moonwell-spruce-overhang-v2.png'),canopy:loadArt('assets/moonwell-art/production/moonwell-canopy-curtains-v1.png'),loam:loadArt('assets/moonwell-art/production/moonwell-loam-patches-v1.png'),luminousPool:loadArt('assets/moonwell-art/production/moonwell-moonlight-pools-v2.png'),eir:loadArt('assets/moonwell-art/production/moonwell-eir-rootwatcher-idle-v1.png'),firefly:loadArt('assets/moonwell-art/production/moonwell-firefly-loop-v4.png'),memory:loadArt('assets/moonwell-art/production/moonwell-memory-loop-v2.png'),moonflower:loadArt('assets/moonwell-art/production/moonwell-moonflower-v2.png'),platform:loadArt('assets/moonwell-art/production/moonwell-root-platform-overhang-v1.png'),foliage:loadArt('assets/moonwell-art/production/moonwell-foliage-variants-v1.png'),ground:loadArt('assets/moonwell-art/production/moonwell-ground-texture-variants-v1.png'),stone:loadArt('assets/moonwell-art/production/moonwell-stone-variants-v1.png'),mushroom:loadArt('assets/moonwell-art/production/moonwell-mushroom-variants-v1.png'),lightPool:loadArt('assets/moonwell-art/production/moonwell-light-pool-variants-v1.png'),bridge:loadArt('assets/moonwell-art/production/moonwell-bridge-segment-v2.png'),rune:loadArt('assets/moonwell-art/production/moonwell-rune-stone-v2.png'),skybell:loadArt('assets/moonwell-art/production/moonwell-skybell-loop-v2.png'),sentinel:loadArt('assets/moonwell-art/production/moonwell-sentinel-tile-v4.png'),altar:loadArt('assets/moonwell-art/production/moonwell-altar-v2.png'),water:loadArt('assets/moonwell-art/production/moonwell-water-tile-v2.png')};
  const keys={},touchKeys={},areas=createAreas();
  const totalFireflies=TOTAL_FIREFLIES;
  const query=new URLSearchParams(location.search),developerScene=query.get('dev')==='scene',requestedArea=Number.parseInt(query.get('area')||'0',10);
  let player={...areas[0].start},area=0,bridge=false,exitState=EXIT_STATES.CLOSED,exitElapsed=0,worldObjects=createWorldObjects(0,false,EXIT_STATES.CLOSED),groundDecor=createGroundDecor(0),runeStep=0,echoAwake=false,echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0},trail=[],trailClock=0,bellsAwake=0,starfallAwake=false,memoryReveal=null,watcherBlessed=false,watcherDialogue=null,walking=false,facing=1,running=false,paused=false,won=false,last=0,step=0,walkClock=0,spawnCue=0;
  const gathered=()=>countLights(areas);
  const remembered=()=>countMemories(areas);
  const allHere=()=>areaComplete(areas[area]);
  const rect=(x,y,w,h,color)=>{ctx.fillStyle=color;ctx.fillRect(x,y,w,h)};
  const loaded=image=>image.complete&&image.naturalWidth;
  const animationFrame=()=>reduce.matches?0:Math.floor(step/12)%4;
  const say=text=>{announcement.textContent=text;hint.textContent=text};
  const inside=(x,y,box)=>x>=box.x&&x<box.x+box.w&&y>=box.y&&y<box.y+box.h;
  const wall=(x,y)=>worldObjects.some(object=>object.solid&&inside(x,y,object));
  const canMove=(x,y)=>!wall(x-5,y-5)&&!wall(x+5,y-5)&&!wall(x-5,y+5)&&!wall(x+5,y+5);
  const syncEchoControl=()=>{echoButton.hidden=area!==2||!running||paused||echoAwake};
  const syncTalkControl=()=>{talkButton.hidden=area!==1||!running||paused||watcherDialogue!==null};
  function tree(object){const {x,y}=object;if(loaded(art.spruce)){const frame=(Math.floor(x/T)+Math.floor(y/T)*3+area)%6;ctx.drawImage(art.spruce,frame*80,0,80,112,x-12,y-40,40,56);return}rect(x+3,y-22,10,38,'#173941');rect(x-8,y-34,32,42,'#0d2a34')}
  function glow(x,y,r,color){const gradient=ctx.createRadialGradient(x,y,0,x,y,r);gradient.addColorStop(0,color);gradient.addColorStop(.42,color);gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(x-r,y-r,r*2,r*2)}
  function firefly(light,index){if(light.got||(light.hidden&&!hiddenLightVisible(area,echoAwake,starfallAwake)))return;const pulse=reduce.matches?1:1+Math.sin((step+index*22)/12)*.35;glow(light.x,light.y,13*pulse,'rgba(255,196,76,.32)');if(loaded(art.firefly))ctx.drawImage(art.firefly,animationFrame()*16,0,16,16,light.x-8,light.y-8,16,16);else{rect(light.x-2,light.y-2,5,5,'#fef08a');rect(light.x-1,light.y-1,2,2,'#fff')}}
  function fairyPlatform(object){if(loaded(art.platform)){const frame=(Number(object.id.at(-1))+area)%2;ctx.drawImage(art.platform,frame*128,0,128,48,object.x-16,object.y-8,64,24)}}
  function exitTree(object){
    const {x,y,state}=object;
    const frame={closed:0,opening:1,revealed:2,open:3}[state];
    if(loaded(art.exitTree)){ctx.drawImage(art.exitTree,frame*80,0,80,112,x-12,y-40,40,56);return}
    tree(object)
  }
  function moonflower(flower){glow(flower.x,flower.y,18,'rgba(189,150,255,.22)');if(loaded(art.moonflower))ctx.drawImage(art.moonflower,flower.x-8,flower.y-8,16,16)}
  function watcher(point){const pulse=reduce.matches?1:1+Math.sin(step/16)*.06;glow(point.x+7,point.y-10,18*pulse,watcherBlessed?'rgba(255,196,76,.3)':'rgba(255,180,68,.22)');if(loaded(art.eir)){const frame=reduce.matches?0:Math.floor(step/28)%4;ctx.drawImage(art.eir,frame*64,0,64,96,point.x-16,point.y-44,32,48)}}
  function openWatcherDialogue(){if(area!==1||!running)return;const point=areas[1].watcher;if(Math.hypot(player.x-point.x,player.y-point.y)>22){say('Eir watches beside the moonflower. Step closer, then talk.');return}memoryDialogue.hidden=true;watcherDialogue='riddle';running=false;Object.keys(keys).forEach(key=>keys[key]=false);Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);syncTalkControl();renderWatcherDialogue()}
  function renderWatcherDialogue(){let node=document.querySelector('#watcher-dialogue');if(!node){node=document.createElement('aside');node.id='watcher-dialogue';node.className='watcher-dialogue';node.setAttribute('role','dialog');node.setAttribute('aria-modal','true');node.setAttribute('data-qa-required','Eir dialogue');canvas.parentElement.append(node)}const portrait='<img class="watcher-dialogue__portrait" src="assets/moonwell-art/production/moonwell-eir-rootwatcher-portrait-v1.png" alt="Eir, Rootwatcher, an older forest guardian holding a warm lantern and root staff">';const finish=()=>{watcherDialogue=null;node.hidden=true;running=true;last=performance.now();syncTalkControl();canvas.focus();requestAnimationFrame(loop)};if(watcherDialogue==='riddle'){node.hidden=false;node.innerHTML=`${portrait}<div class="watcher-dialogue__body"><strong>${WATCHER_DIALOGUE.name}</strong><p>I kept this crossing while the paths forgot themselves. ${WATCHER_DIALOGUE.riddle}</p><div class="watcher-dialogue__choices"><button data-answer="0">${WATCHER_DIALOGUE.choices[0]}</button><button data-answer="1">${WATCHER_DIALOGUE.choices[1]}</button></div><button class="watcher-dialogue__leave">Leave</button></div>`;node.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>{const result=watcherChoiceResult(Number(button.dataset.answer));watcherDialogue=result.correct?'blessed':'clue';if(result.correct)watcherBlessed=true;renderWatcherDialogue()});node.querySelector('.watcher-dialogue__leave').onclick=finish;node.querySelector('[data-answer="0"]').focus();return}const result=watcherChoiceResult(watcherDialogue==='blessed'?0:1);node.innerHTML=`${portrait}<div class="watcher-dialogue__body"><strong>${WATCHER_DIALOGUE.name}</strong><p>${result.reply}</p><button class="watcher-dialogue__continue">${result.correct?'Carry the clue':'Hear the riddle again'}</button><button class="watcher-dialogue__leave">Leave</button></div>`;node.querySelector('.watcher-dialogue__continue').onclick=()=>{if(result.correct)finish();else{watcherDialogue='riddle';renderWatcherDialogue()}};node.querySelector('.watcher-dialogue__leave').onclick=finish;node.querySelector('.watcher-dialogue__continue').focus()}
  function memory(place,index){if(!place.memory||place.memory.got)return;const token=place.memory;const pulse=reduce.matches?1:1+Math.sin((step+index*17)/15)*.12;glow(token.x,token.y,9*pulse,'rgba(226,232,240,.13)');if(loaded(art.memory))ctx.drawImage(art.memory,animationFrame()*16,0,16,16,token.x-8,token.y-8,16,16);else{rect(token.x-3,token.y-4,6,8,'#e2e8f0');rect(token.x-1,token.y-2,2,4,'#c4b5fd')}}
  function memoryRevealBox(){return memoryRevealBoxForPlayer(player.y)}
  function memoryRevealLines(text){const words=text.split(' '),lines=[''];for(const word of words){const next=lines[lines.length-1]?`${lines[lines.length-1]} ${word}`:word;if(next.length>MEMORY_REVEAL_LAYOUT.maxLineChars)lines.push(word);else lines[lines.length-1]=next}return lines.slice(0,MEMORY_REVEAL_LAYOUT.maxLines)}
  function drawMemoryReveal(){if(!memoryReveal){memoryDialogue.hidden=true;return}const state=memoryRevealStateAt(memoryReveal.elapsed,reduce.matches);if(state==='hidden'){memoryReveal=null;memoryDialogue.hidden=true;return}const box=memoryRevealBox();memoryDialogue.hidden=false;memoryDialogue.dataset.band=box.y===MEMORY_REVEAL_LAYOUT.topY?'top':'bottom';memoryDialogue.classList.toggle('is-fading',state==='fading'&&!reduce.matches);memoryDialogue.querySelector('p').textContent=memoryReveal.text}
  function drawSpawnCue(){const remaining=(spawnCue-performance.now())/1000;if(remaining<=0)return;ctx.save();ctx.globalAlpha=Math.min(1,remaining)*.8;const color='#f0c76a';rect(player.x-15,player.y-10,3,3,color);rect(player.x+12,player.y-10,3,3,color);rect(player.x-10,player.y-18,3,3,color);rect(player.x+7,player.y-18,3,3,color);rect(player.x-7,player.y+1,3,2,color);rect(player.x+4,player.y+1,3,2,color);ctx.restore()}
  function playerKeeper(){if(keeperArt.complete&&keeperArt.naturalWidth){const frame=walking&&!reduce.matches?Math.floor(walkClock/.11)%4:0;ctx.save();ctx.translate(player.x,player.y-22);ctx.scale(facing,1);ctx.drawImage(keeperArt,frame*16,0,16,16,-10,0,20,24);ctx.restore();return}rect(player.x-6,player.y-15,12,18,'#8d6dd2');rect(player.x+4,player.y-5,3,3,'#f0c76a')}
  function drawGroundDetail(item){const {x,y,kind}=item,variant=(Math.floor(x/T)*3+Math.floor(y/T)+area)%3;if(kind==='moon'&&loaded(art.lightPool)){ctx.drawImage(art.lightPool,variant*T,0,T,T,x,y,T,T);return}if((kind==='shadow'||kind==='needles'||kind==='root')&&loaded(art.ground)){ctx.save();ctx.globalAlpha=kind==='shadow'?.58:.86;ctx.drawImage(art.ground,variant*T,0,T,T,x,y,T,T);ctx.restore();return}if(kind==='fern'&&loaded(art.foliage)){ctx.drawImage(art.foliage,variant*T,0,T,T,x,y,T,T);return}if(kind==='stone'&&loaded(art.stone)){ctx.drawImage(art.stone,variant*T,0,T,T,x,y,T,T);return}if(kind==='mushroom'&&loaded(art.mushroom)){ctx.drawImage(art.mushroom,(variant%2)*T,0,T,T,x,y,T,T);return}if(kind==='firefly'&&loaded(art.firefly)){ctx.save();ctx.globalAlpha=.78;ctx.drawImage(art.firefly,animationFrame()*T,0,T,T,x,y,T,T);ctx.restore();return}if(kind==='shadow'){rect(x,y+10,16,6,'#12323d');rect(x+4,y+6,12,4,'#12323d')}else if(kind==='moon'){rect(x+1,y+8,15,5,'#4f8f94');rect(x+5,y+5,11,3,'#4f8f94');rect(x+2,y+13,9,2,'#79b4b5')}else if(kind==='fern'){rect(x+7,y+7,2,8,'#78a77d');rect(x+3,y+8,4,2,'#4f8b68');rect(x+9,y+5,4,2,'#4f8b68');rect(x+2,y+12,5,2,'#4f8b68')}else if(kind==='stone'){rect(x+4,y+10,8,4,'#6f8790');rect(x+6,y+8,5,2,'#91a9ad');rect(x+3,y+14,10,1,'#102e38')}else if(kind==='needles'){rect(x+3,y+9,9,1,'#5a806b');rect(x+5,y+12,8,1,'#3f6b59');rect(x+9,y+7,4,1,'#78a77d')}else if(kind==='root'){rect(x+2,y+11,12,2,'#76513c');rect(x+8,y+8,2,4,'#9a704e');rect(x+12,y+13,3,1,'#4f8b68')}else if(kind==='mushroom'){rect(x+6,y+9,5,3,'#b99078');rect(x+8,y+12,1,3,'#d4c4a1');rect(x+5,y+10,2,1,'#d2a3af')}else{rect(x+7,y+8,2,2,'#d6e6df');rect(x+9,y+7,1,1,'#f0c76a')}}
  function worldObject(object){if(object.kind==='tree')tree(object);else if(object.kind==='exit-tree')exitTree(object);else if(object.kind==='platform')fairyPlatform(object);else if(object.kind==='water'){rect(object.x,object.y,T,T,'#071b3e');if(loaded(art.water))ctx.drawImage(art.water,object.x,object.y)}else if(object.kind==='bridge'&&loaded(art.bridge))ctx.drawImage(art.bridge,object.frame*T,0,T,T,object.x,object.y,T,T);else if(object.kind==='sentinel'&&loaded(art.sentinel))ctx.drawImage(art.sentinel,object.x,object.y,object.w,object.h)}
  function rune(stone,index){const active=!echoAwake&&((index===0&&runeStep===0)||(index===1&&runeStep===1)||(index===2&&runeStep===2));const held=echo.active&&echo.holding&&index===0;glow(stone.x,stone.y,held?18:active?15:8,held?'rgba(103,232,249,.26)':active?'rgba(216,180,254,.2)':'rgba(148,163,184,.08)');if(loaded(art.rune))ctx.drawImage(art.rune,stone.x-8,stone.y-8,16,16)}
  function echoKeeper(){if(!echo.active)return;const pulse=reduce.matches?1:1+Math.sin(step/7)*.08;glow(echo.x,echo.y-8,heldRadius(pulse),'rgba(103,232,249,.16)');ctx.save();ctx.globalAlpha=echo.holding?.56:.38;ctx.translate(echo.x,echo.y-16);if(keeperArt.complete&&keeperArt.naturalWidth)ctx.drawImage(keeperArt,0,0,16,16,-8,0,16,16);else{rect(-5,3,10,11,'#67e8f9');rect(-3,0,6,5,'#e0f2fe')}ctx.restore()}
  function heldRadius(pulse){return echo.holding?12*pulse:8*pulse}
  function bell(bell){const lit=bell.lit;glow(bell.x,bell.y,lit?16:9,lit?'rgba(253,224,71,.18)':'rgba(125,211,252,.08)');if(loaded(art.skybell))ctx.drawImage(art.skybell,animationFrame()*32,0,32,48,bell.x-16,bell.y-34,32,48)}
  const moonlightLayouts=[[[42,122,2],[132,70,1],[224,18,0]],[[30,32,1],[132,120,0],[228,118,2]],[[38,118,0],[150,74,2],[232,20,1]],[[36,26,1],[128,118,0],[218,72,2]]];
  function drawLoamFloor(){const base=['#0a242b','#0b2830','#0c2130','#09242d'][area];rect(0,0,W,H,base);if(!loaded(art.loam)){for(let y=0;y<H;y+=16)for(let x=0;x<W;x+=16)rect(x,y,16,16,(x/16+y/16+area)%2?'#12333a':'#102d35');return}ctx.save();ctx.globalAlpha=.94;let row=0;for(let y=-8;y<H;y+=34,row++)for(let x=-16-(row%2)*21;x<W;x+=42){const frame=(row*3+Math.floor((x+16)/42)+area)%4;ctx.drawImage(art.loam,frame*128,0,128,96,x,y,64,48)}ctx.restore()}
  function drawMoonlightPools(){if(!loaded(art.luminousPool))return;ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=.7;for(const [x,y,frame] of moonlightLayouts[area])ctx.drawImage(art.luminousPool,frame*128,0,128,96,x,y,64,48);ctx.restore()}
  function drawCanopyBackdrop(){if(!loaded(art.canopy))return;ctx.save();ctx.globalAlpha=.96;ctx.drawImage(art.canopy,(area%2)*256,0,256,112,-6,-3,128,56);ctx.drawImage(art.canopy,((area+1)%2)*256,0,256,112,96,-4,128,56);ctx.drawImage(art.canopy,(area%2)*256,0,256,112,202,-2,128,56);ctx.restore()}
  function drawAtmosphere(){const vignette=ctx.createRadialGradient(W/2,H/2,72,W/2,H/2,190);vignette.addColorStop(0,'rgba(2,9,20,0)');vignette.addColorStop(.72,'rgba(2,9,20,.08)');vignette.addColorStop(1,'rgba(2,6,23,.48)');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H)}
  function draw(){ctx.setTransform(RENDER_SCALE,0,0,RENDER_SCALE,0,0);ctx.imageSmoothingEnabled=false;drawLoamFloor();drawMoonlightPools();worldObjects.filter(object=>object.kind==='water'||object.kind==='bridge').forEach(worldObject);groundDecor.forEach(drawGroundDetail);drawCanopyBackdrop();const place=areas[area],entities=[];worldObjects.filter(object=>object.kind!=='water'&&object.kind!=='bridge').forEach(object=>entities.push({y:object.y+object.h,draw:()=>worldObject(object)}));if(area===1){entities.push({y:place.flower.y,draw:()=>moonflower(place.flower)},{y:place.watcher.y+4,draw:()=>watcher(place.watcher)})}if(area===2){place.runes.forEach((stone,index)=>entities.push({y:stone.y,draw:()=>rune(stone,index)}));if(echo.active)entities.push({y:echo.y,draw:echoKeeper});if(echoAwake)glow(188,128,28,'rgba(253,224,71,.14)')}if(area===3){place.bells.forEach(item=>entities.push({y:item.y+10,draw:()=>bell(item)}));if(starfallAwake){glow(190,105,46,'rgba(253,224,71,.14)');if(loaded(art.altar))entities.push({y:112,draw:()=>ctx.drawImage(art.altar,174,80,32,32)})}}if(place.memory&&!place.memory.got)entities.push({y:place.memory.y,draw:()=>memory(place,area)});place.lights.forEach((light,index)=>entities.push({y:light.y,draw:()=>firefly(light,index)}));entities.push({y:player.y,draw:()=>{drawSpawnCue();playerKeeper()}});entities.sort((a,b)=>a.y-b.y).forEach(entity=>entity.draw());rect(0,0,W,H,'rgba(3,12,24,.08)');if(gathered())rect(0,0,W,H,`rgba(255,196,76,${.012*gathered()})`);drawAtmosphere();drawMemoryReveal()}
  function refreshWorld(){worldObjects=createWorldObjects(area,bridge,exitState);groundDecor=createGroundDecor(area)}
  function arrive(next){area=next;bridge=false;exitState=EXIT_STATES.CLOSED;exitElapsed=0;refreshWorld();player={...areas[next].start};trail=[];echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0};areaLabel.textContent=`Area: ${areas[next].name}`;if(next===1)say('Moonlight opens Moonroot Crossing. The dark water is impassable until the moonflower reveals its safe bridge. Eir watches nearby.');else if(next===2)say('A lighted forest opening leads to Whispering Hollow. Touch the first violet rune, then find the second and press E or Echo.');else say('A lighted forest opening leads to Starfall Grove. Ring each skybell to call its fallen lights from the canopy.');syncEchoControl();syncTalkControl()}
  function finish(){won=true;running=false;modal.innerHTML='<div class="card"><h2>The Moonwell shines again.</h2><p>Starfall Grove returns its bright fragments. Eight fireflies return to the Lost Lantern, and moonlight spills through every path before dawn.</p><p>The young keeper has carried the forest home—and the forest remembers the way.</p><button id="again">Walk again</button></div>';modal.hidden=false;document.querySelector('#again').onclick=()=>location.reload();say('The Lost Lantern burns bright before dawn.')}
  function resume(){paused=false;pauseButton.hidden=false;modal.hidden=true;running=true;syncEchoControl();syncTalkControl();last=performance.now();canvas.focus();say('The forest waits.');requestAnimationFrame(loop)}
  function pause(){if(!running||won)return;running=false;paused=true;pauseButton.hidden=true;syncEchoControl();syncTalkControl();Object.keys(keys).forEach(key=>keys[key]=false);Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);modal.innerHTML='<div class="card"><h2>The forest waits.</h2><p>Your lantern light is safe. Take a breath, then continue when you are ready.</p><button id="resume">Continue</button><button id="restart">Start again</button></div>';modal.hidden=false;const resumeButton=document.querySelector('#resume');resumeButton.onclick=resume;document.querySelector('#restart').onclick=()=>location.reload();resumeButton.focus();say('Moonwell is paused. Press P, Escape, or Continue when you are ready.')}
  pauseButton.onclick=()=>{if(paused)resume();else pause()};
  function resolveEcho(){echoAwake=true;echo.active=false;syncEchoControl();say('Your echo holds the first rune as the third answers. A hidden firefly rises beside the old stone arch.')}
  function touchRune(){const runes=areas[2].runes;if(runeStep===0&&nearPoint(player,runes[0])){runeStep=1;say('The first echo-stone remembers your steps. Walk to the second violet rune, then press E or Echo.')}if(canResolveEchoRune(runeStep,echo.active&&echo.holding,player,runes))resolveEcho()}
  function castEcho(){if(!running||area!==2||echoAwake||echo.active)return;const runes=areas[2].runes;if(runeStep===0){say('The lantern needs a remembered path. Touch the first violet rune first.');return}if(!nearPoint(player,runes[1])){say('Stand by the second violet rune, then press E or Echo.');return}const replay=createEchoReplay(trail,runes[0]);if(!replay.length){say('The lantern cannot find the first rune in your recent steps. Touch it again, then return here.');runeStep=0;return}echo={active:true,holding:false,path:replay,index:0,x:replay[0].x,y:replay[0].y,holdTime:4.5};runeStep=2;say('A delayed echo retraces your path. Reach the third rune while it returns to hold the first.');syncEchoControl()}
  function updateEcho(dt){if(!echo.active)return;if(echo.holding){echo.holdTime-=dt;if(echo.holdTime<=0){echo={active:false,holding:false,path:[],index:0,x:0,y:0,holdTime:0};runeStep=0;say('The echo fades into the hollow. Touch the first rune and try again.');syncEchoControl()}return}let distance=96*dt;while(distance>0&&echo.index<echo.path.length-1){const next=echo.path[echo.index+1],dx=next.x-echo.x,dy=next.y-echo.y,gap=Math.hypot(dx,dy);if(gap<=distance){echo.x=next.x;echo.y=next.y;echo.index++;distance-=gap}else{echo.x+=dx/gap*distance;echo.y+=dy/gap*distance;distance=0}}if(echo.index===echo.path.length-1){echo.x=areas[2].runes[0].x;echo.y=areas[2].runes[0].y;echo.holding=true;say('Your echo holds the first rune. Reach the third violet rune before it fades.')}}
  function touchBell(){for(const bell of areas[3].bells){if(!bell.lit&&Math.hypot(player.x-bell.x,player.y-bell.y)<15){bell.lit=true;bellsAwake++;if(bellsAwake===areas[3].bells.length){starfallAwake=true;say('Three skybells answer together. Two fallen lights drift down through the open canopy.')}else say(`A skybell rings above the grove. ${areas[3].bells.length-bellsAwake} still wait in the blue dark.`);break}}}
  function update(dt){if(memoryReveal)memoryReveal.elapsed+=dt;let dx=0,dy=0,speed=65*dt;if(keys.up||touchKeys.up)dy-=speed;if(keys.down||touchKeys.down)dy+=speed;if(keys.left||touchKeys.left)dx-=speed;if(keys.right||touchKeys.right)dx+=speed;if(dx&&dy){dx*=.707;dy*=.707}if(dx)facing=dx<0?-1:1;const beforeX=player.x,beforeY=player.y;if(canMove(player.x+dx,player.y))player.x+=dx;if(canMove(player.x,player.y+dy))player.y+=dy;walking=player.x!==beforeX||player.y!==beforeY;if(walking)walkClock+=dt;const place=areas[area];if(area===2){trailClock+=dt;if(walking||trailClock>.08){trail.push({x:player.x,y:player.y});trailClock=0;if(trail.length>1800)trail.shift()}updateEcho(dt)}if(place.memory&&!place.memory.got&&Math.hypot(player.x-place.memory.x,player.y-place.memory.y)<12){place.memory.got=true;memoryReveal={text:place.memory.text,elapsed:0};memoryCount.textContent=`Memories: ${remembered()} / 3`;say(`Forest memory found. ${place.memory.text}`)}if(area===1&&!bridge&&Math.hypot(player.x-place.flower.x,player.y-place.flower.y)<16){bridge=true;refreshWorld();say('The moonflower reveals a safe wooden bridge across the full water crossing.')}if(area===2&&!echoAwake)touchRune();if(area===3&&!starfallAwake)touchBell();place.lights.forEach(light=>{if(!light.got&&(!light.hidden||hiddenLightVisible(area,echoAwake,starfallAwake))&&Math.hypot(player.x-light.x,player.y-light.y)<12){light.got=true;count.textContent=`Fireflies: ${gathered()} / ${totalFireflies}`;say(allHere()?'The border tree shivers; a moonlit seam begins to open.':`A firefly joins you! ${totalFireflies-gathered()} still wander.`)}});if(allHere()&&exitState===EXIT_STATES.CLOSED){exitState=EXIT_STATES.OPENING;exitElapsed=0;refreshWorld()}if(exitState!==EXIT_STATES.CLOSED&&exitState!==EXIT_STATES.OPEN){const nextState=exitStateAt(exitElapsed);if(nextState!==exitState){exitState=nextState;refreshWorld();if(exitState===EXIT_STATES.REVEALED)say('The tree parts around a visible glimmer, but its roots still hold the path.');if(exitState===EXIT_STATES.OPEN)say('The glimmer passage is fully parted. Walk through the open tree.')}exitElapsed+=dt}if(exitState===EXIT_STATES.OPEN&&!won&&Math.hypot(player.x-place.home.x,player.y-place.home.y)<17){const next=nextAreaIndex(area,areas);if(next!==null)arrive(next);else finish()}}
  function loop(time){if(!running)return;const dt=Math.min(.04,(time-last)/1000||0);last=time;step+=dt*60;update(dt);draw();requestAnimationFrame(loop)}
  async function begin(input){const userInitiated=input===true||input?.isTrusted===true;if(coarse.matches&&!portrait.matches){document.body.classList.add('playing');window.scrollTo(0,1);try{if(userInitiated&&document.fullscreenEnabled&&!document.fullscreenElement)await document.documentElement.requestFullscreen();if(userInitiated&&screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{}}paused=false;modal.hidden=true;running=true;spawnCue=performance.now()+(reduce.matches?1100:2800);syncEchoControl();syncTalkControl();last=performance.now();canvas.focus();say('Arrow keys or WASD move · gather the three lights in this glade.');requestAnimationFrame(loop)}
  function gate(){if(coarse.matches&&portrait.matches){document.body.classList.remove('playing');modal.hidden=false;running=false}else if(!running&&!won)modal.hidden=false;syncEchoControl();syncTalkControl()}start.onclick=begin;echoButton.onclick=castEcho;talkButton.onclick=openWatcherDialogue;[coarse,portrait].forEach(query=>query.addEventListener('change',gate));addEventListener('keydown',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right'}[event.key];if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(event.key))event.preventDefault();if(event.key==='Enter'&&!running&&!won&&!portrait.matches)begin();if(event.key==='e'||event.key==='E')castEcho();if(event.key==='f'||event.key==='F')openWatcherDialogue();if(event.key==='j'||event.key==='J'){const notes=areas.filter(place=>place.memory?.got).map(place=>place.memory.text);say(notes.length?`Forest memories: ${notes.join(' ')} ${3-notes.length} still wait.`:'No forest memories yet. Look for pale keepsakes beside the paths.')}if(direction)keys[direction]=true});addEventListener('keyup',event=>{const direction={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right'}[event.key];if(direction)keys[direction]=false});const touch=document.querySelector('.touch');let touchPointer;function steer(event){const bounds=touch.getBoundingClientRect(),x=event.clientX-(bounds.left+bounds.width/2),y=event.clientY-(bounds.top+bounds.height/2),direction=Math.abs(x)>Math.abs(y)?x<0?'left':'right':y<0?'up':'down';Object.keys(touchKeys).forEach(key=>touchKeys[key]=false);touchKeys[direction]=true}function stopSteering(){touchPointer=undefined;Object.keys(touchKeys).forEach(key=>touchKeys[key]=false)}touch.addEventListener('contextmenu',event=>event.preventDefault());touch.addEventListener('pointerdown',event=>{event.preventDefault();touchPointer=event.pointerId;try{touch.setPointerCapture(event.pointerId)}catch{}steer(event)});touch.addEventListener('pointermove',event=>{if(event.pointerId===touchPointer)steer(event)});touch.addEventListener('pointerup',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('pointercancel',event=>{if(event.pointerId===touchPointer)stopSteering()});touch.addEventListener('lostpointercapture',stopSteering);draw();gate()
  addEventListener('keydown',event=>{if((event.key==='p'||event.key==='P'||event.key==='Escape')&&!won){event.preventDefault();if(paused)resume();else pause()}});
  if(developerScene&&Number.isInteger(requestedArea)&&requestedArea>=0&&requestedArea<areas.length){area=requestedArea;player={...areas[area].start};bridge=area===1;refreshWorld();runeStep=areas[2].runes.length;echoAwake=true;bellsAwake=areas[3].bells.length;starfallAwake=true;areaLabel.textContent=`Area: ${areas[area].name}`;modal.hidden=true;running=true;say(`Developer scene preview: ${areas[area].name}`);window.__moonwellAudit=Object.freeze({area:()=>area,name:()=>areas[area].name,waterBlocked:()=>wall(80,100),bridgePassable:()=>wall(160,100)===false,sentinelBlocked:()=>wall(160,110),canvas:()=>({logicalWidth:W,logicalHeight:H,width:canvas.width,height:canvas.height,renderScale:RENDER_SCALE}),exitState:()=>exitState,previewExit:state=>{exitState=state;refreshWorld();draw();return{state,blocked:wall(areas[area].home.x,areas[area].home.y)}},previewMemory:seconds=>{memoryReveal={text:areas[area].memory.text,elapsed:seconds};draw();return{state:memoryRevealStateAt(seconds,reduce.matches),box:memoryRevealBox()}},previewWatcher:()=>{area=1;player={...areas[1].watcher};running=true;openWatcherDialogue();return{open:watcherDialogue,point:areas[1].watcher}},transition:()=>{areas[area].lights.forEach(light=>light.got=true);player={...areas[area].home};update(0);return{area,exitState,won}},advanceExit:seconds=>{update(seconds);return{area,exitState,blocked:wall(areas[area].home.x,areas[area].home.y)}}});last=performance.now();requestAnimationFrame(loop)}
})();
(()=>{const start=document.querySelector('#start'),modal=document.querySelector('#modal'),reduce=matchMedia('(prefers-reduced-motion: reduce)'),begin=start?.onclick;if(!start||!begin)return;const pages=[['When the Moonwell dimmed, the forest began to forget.','Paths lost their names. Fireflies carried the last bright memories into the blue dark.'],['You are the last Keeper.','Gather the scattered memories, wake the old crossings, and bring the Lost Lantern home before the forest forgets you too.']];let page=0,timer;const show=()=>{const [title,copy]=pages[page];modal.innerHTML=`<div class="card prologue-card"><h2>${title}</h2><p>${copy}</p><button id="prologue-next">${page===pages.length-1?'Light the way':'Continue'}</button><button id="prologue-skip">Skip prologue</button></div>`;modal.hidden=false;const advance=event=>{clearTimeout(timer);if(++page<pages.length)show();else begin(event)};document.querySelector('#prologue-next').onclick=advance;document.querySelector('#prologue-skip').onclick=event=>{clearTimeout(timer);begin(event)};if(!reduce.matches)timer=setTimeout(advance,6200)};start.onclick=()=>{page=0;show()};addEventListener('keydown',event=>{if(!modal.hidden&&document.querySelector('#prologue-next')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();document.querySelector('#prologue-next').click()}})})();
